### ISSUE TITLE
✨ Filled half star

### ISSUE THREAD

**Issue by jd-solanki** [lucide-icons/lucide#864] opened 2022-11-01 06:47 UTC
## Icon Request

* Icon name: filled half star
* Use case: For using it as a rating component
* _Screenshots_ of similar icons:
![Screenshot 2022-11-01 at 12 16 30 PM](https://user-images.githubusercontent.com/47495003/199175224-dabf5c0b-18b9-4f10-afcb-b8f8a0f617e7.png)

## Additional comments

We already have a half star but we don't have filled so we can't use it to demonstrate the ratings like 2.5 or 3.5.

**Comment by karsa-mistmere** [comment] 2022-11-01 07:04
I'm closing this issue as a duplicate of #407 and #458.

**Closed by karsa-mistmere** 2022-11-01 07:04 UTC
Labels: 🙌 icon request
