### ISSUE TITLE
Filled versions of icons

### ISSUE THREAD

**Issue by tryoxiss** [lucide-icons/lucide#893] opened 2022-11-26 03:25 UTC
I know this has been suggested before and it was refused because the `fill: ` property does the same thing, but it dosent always. For most (probably 60-70% of the icons) it works great, no issues there. But it does break quite a few (notably the file/foleder type icons) 

(fill: currentColor) 
![image](https://user-images.githubusercontent.com/94419893/204068134-e18ebf44-bb16-4fd2-a81b-6ae884e69e4e.png)

And you can make th stroke/color to transparent, but I think that does more harm than good: 
(fill: currentColor; color: transparent)
![image](https://user-images.githubusercontent.com/94419893/204068192-6d2b6fbf-37e5-4ebf-9154-b06c7ebe8c0a.png)

I'm not sure if theres an easy fix to this, or if it would require a lot of work. But it would be nice for those icons that break to work when you set a fill, so it looks good even with those.

**Comment by jd-solanki** [comment] 2022-12-01 05:50
I do want to use lucide icons in my lib - [Anu](https://anu-vue.netlify.app/guide/components/alert.html) but due to missing filled icons. I am using another icon lib.

**Comment by nandorojo** [comment] 2022-12-02 23:43
This would be awesome.

**Comment by tryoxiss** [comment] 2022-12-10 02:55
@nandorojo yeah I didn't know how hard it would be, in the case of ticket I think it works well enough to be useable when its just filled but there certinly are some that seem tricky.

**Comment by nandorojo** [comment] 2022-12-10 04:01
yeah tbh it probably requires making new icons

**Comment by tryoxiss** [comment] 2022-12-10 06:21
Yeah... if someone were to do that, how would they do it? If its a simple (ish) process I could see if I could do some of that. (No gurnuntees, my interests and hobbies are very on and off but ive been wanting to do vector illistration for a bit and this may be a good excuse for me)

**Comment by tryoxiss** [comment] 2023-01-13 02:16
I did a bit of work on what I imagine some of the icons looking like when filled, and came up with some basic design rules for it. 

1. if the icon consists of one or more, large, non-intersecting shapes, fill fill them. 
![image](https://user-images.githubusercontent.com/94419893/212220848-da5ce984-d533-4b34-bf85-8ee3c61ad3e5.png)
![image](https://user-images.githubusercontent.com/94419893/212221256-0da6f147-3056-4450-8943-d4bdfd88e59c.png)
![image](https://user-images.githubusercontent.com/94419893/212221329-64c8a9c0-26e8-4ec8-99e1-236c5e183c06.png)


2. if the icon is one large shape, with smaller ones inside, fill the inner items -- this one im not sure about, the alternative is to fill it and make the inner bits transparent, but thats complex and im dumb and couldn'tfigure out how to do that. 
![image](https://user-images.githubusercontent.com/94419893/212220905-ee5d3830-ea17-412d-a375-ffa5be8107d2.png)
![image](https://user-images.githubusercontent.com/94419893/212221031-65309278-117f-44cf-a52e-1343764c9be4.png)


3. If the icon consists of two large disctinct sections, fill whichever feels more right, generally the larger one -- also not sure abt this one
![image](https://user-images.githubusercontent.com/94419893/212221016-a2c0dfb1-598b-4e74-ac5f-71cd63488ddf.png)
![image](https://user-images.githubusercontent.com/94419893/212221214-4d391825-4bde-424c-9cae-470192462b55.png)

4. if the icon is a large shape, with missing/sections in them, leave them transparent. 
(White parts are ones that I imagine to be transparent) 
![image](https://user-images.githubusercontent.com/94419893/212221524-f44a7222-1f49-426f-973c-44b344b5fba1.png)


5. if the icon contyains the cross, ignore it in your design and follow the otrhewr ruiles
![image](https://user-images.githubusercontent.com/94419893/212221139-9c50ddf0-0be4-4f0b-8524-51096d534c44.png)

Still not great and needs a lot of refining, but even with my terrible SVG-ing abbiluty I still think it they look really good, and using the exisitng icons would be much less work than a new icon set like some people said. Its still editing almost every icon, but much more manageable.

**Comment by karsa-mistmere** [comment] 2023-01-18 17:28
Some of these suggestions are no brainers, but some I'm not quite sure about:
![image](https://user-images.githubusercontent.com/17746067/213251403-abca7337-9fd0-4602-8fec-4e13d1533236.png)
Column 1: our current icons
Column 2: @tryoxiss' proposal
Column 3: alternate approach A
Column 4: alternate approach B (same as Col3 if missing).

I think Col4 is the sure winner here, since:
- Col2 adds too much visual weight to certain elements
- Col3 will introduce some unpredictable clipping where elements meet.

**Comment by tryoxiss** [comment] 2023-01-18 21:14
Yeah, looking at proper versions I agree that column 4 is 100% better. And yeah, column 4 is defintely better than column 3, since in the image-cross one it creates a weird small filled area and I can imagine that will happen with other icons too.

**Comment by tryoxiss** [comment] 2023-01-19 05:29
Ok, I spent some time trying to put the changes in column 4 into words and I think I have some rules for it: 

Forgive the probably bad termonolgy, I have very limited experince with vector graphics and icon design. 

General Rules: 
1. Fill all shapes within the icon
2. If any lines exist within the icon, make then cutout/transparent instead of solid. Bring them outside of the shape if they go to the edge, make them extend out to make a clean line. 
3. If two icons would inserset, identify the main object (e.g., the pencil in the edit icon) and surround it with a transparent stroke. 

Alternate Approach A: 
4. If lines within the shape form thier own isolates shape (e.g., the sun and mountian in row 3 column 4), make it and its outline cutout. But make sure to keep any surrounding outline around them, such as in the picture icon. 

Alternate Appraoch B: 
4. If lines within the shape form thier own isolates shape (e.g., the sun and mountian in row 3 column 4), make its outline cutout, but keep the inner part filled. Exrtend it past to penetrate any surrounding border lines.

**Comment by karsa-mistmere** [comment] 2023-04-27 15:02
Closed as duplicate of #815. Continue discussions in #458

**Closed by karsa-mistmere** 2023-04-27 15:02 UTC
Labels: 🙌 icon request
