### ISSUE TITLE
Accessibility improvements 

### ISSUE THREAD

**Issue by dtrucs** [lucide-icons/lucide#1171] opened 2023-04-28 14:04 UTC
In terms of accessibility, there are two types of inline SVG (https://www.w3.org/WAI/standards-guidelines/act/rules/7d6734/)

## Informative icon:
- Icon with `title` (and possibly `desc`) tags. 
- Icon with label attributes such as `aria-label` or `aria-labelledby`.

Informative icon needs an extra "role" attribute.

## Decorative Icon
- Icon intended for decoration.

Decorative icon needs an extra "aria-hidden" attribute.

## Suggestion

At present, these attributes can be set "manually".
My request is to add some default attributes if a label and/or children tags are set or not.

Something like (I'm using the React template, I can open a pull request if needed) :

```jsx
const createLucideIcon = (iconName: string, iconNode: IconNode) => {
  const Component = forwardRef<SVGSVGElement, LucideProps>(
    ({ color = 'currentColor', size = 24, strokeWidth = 2, absoluteStrokeWidth, children, ...rest }, ref) => {
      const attributesRelatedToA11y = children || rest['aria-label'] || rest['aria-labelledby']
        // https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/img_role#svg_and_roleimg
        ? { role: 'image' }
        : { ['aria-hidden']: true };
      return createElement(
        'svg',
        {
          ref,
          ...defaultAttributes,
          ...attributesRelatedToA11y,
          width: size,
          height: size,
          stroke: color,
          strokeWidth: absoluteStrokeWidth ? Number(strokeWidth) * 24 / Number(size) : strokeWidth,
          className: `lucide lucide-${toKebabCase(iconName)}`,
          ...rest,
        },
        [
          ...iconNode.map(([tag, attrs]) => createElement(tag, attrs)),
          ...(
            (Array.isArray(children) ? children : [children]) || []
          )
        ],
      )
    },
  );
```

NB: If a user calls an informative icon and defines an explicit `role` such as `role="graphics-document"`, it will replace the default `role="image"`

**Comment by karsa-mistmere** [comment] 2023-04-28 14:14
In part a duplicate of #477

**Closed by karsa-mistmere** 2023-04-28 14:14 UTC
