### ISSUE TITLE
Memory/Ram Icon

### ISSUE THREAD

**Issue by YesImSevy** [lucide-icons/lucide#542] opened 2022-03-27 06:52 UTC
## Icon Request

* Icon name: Ram/Memory
* Use case: Show ram amount on a server, etc
* _Screenshots_ of similar icons:
https://fontawesome.com/icons/memory?s=solid

**Comment by delnyn** [comment] 2022-04-02 22:36
that's a good idea, but recreating the one you sent while respecting the guidelines seems impossible. we would need to make some exploration

**Comment by ericfennis** [comment] 2022-04-06 09:49
@raphael141714 created on in #527 , but it does need some refactoring to match the guidelines.

**Comment by YesImSevy** [comment] 2022-10-21 17:51
> 

I mean it looks pretty much exactly like a stick of ram just not as wide when you look at like thin for example

**Comment by karsa-mistmere** [comment] 2023-04-27 15:21
Closed as duplicate of #527

**Closed by karsa-mistmere** 2023-04-27 15:21 UTC
Labels: 🙌 icon request
