### ISSUE TITLE
Transportation icons for "Walking" or "Running"

### ISSUE THREAD

**Issue by matthiasfeist** [lucide-icons/lucide#2342] opened 2024-07-29 12:14 UTC
### Icon name

Walk

### Use cases

In the transportation category, there are all kinds of transportation vehicles, but an icon showing someone walking (or running) is missing.
The closest there is right now is the "footprints" icon, but that's not the same in my opinion.

### Design ideas

A small stick figure walking from the left to the right (to be aligned with the "bike" icon.

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by karsa-mistmere** [comment] 2024-07-29 12:18
Duplicate of #609

**Closed by karsa-mistmere** 2024-07-29 12:18 UTC
Labels: 🙌 icon request
