### ISSUE TITLE
Gender icons: female, male, transgender, fluid

### ISSUE THREAD

**Issue by teinett** [lucide-icons/lucide#2240] opened 2024-06-22 16:37 UTC
### Icon name

gender, male, female, transgender, fluid

### Use cases

Website sections that have gender specific content

I checked all issues and found link to issue https://github.com/lucide-icons/lucide/issues/119 and pull request https://github.com/feathericons/feather/pull/46, but for some reason gender icons are not in Feather icon pack or Lucide pack

### Design ideas

Male:
![image](https://github.com/lucide-icons/lucide/assets/1038168/72dbb124-a8e4-4177-8b6a-bef8b4a6350e)

Female:
![image](https://github.com/lucide-icons/lucide/assets/1038168/1322c2b2-74a8-4cf9-a135-604740406212)

Transgender:
![image](https://github.com/lucide-icons/lucide/assets/1038168/3d92ca78-6386-4ac6-98b6-032d51b297db)

Fluid:
![image](https://github.com/lucide-icons/lucide/assets/1038168/b8ca6bb0-55f6-4897-ab86-513badefb7bb)

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by jguddas** [comment] 2024-06-22 20:18
Duplicate of #560

**Closed by jguddas** 2024-06-22 20:18 UTC
Labels: 🙌 icon request

**Comment by teinett** [comment] 2024-06-24 12:51
@jguddas you closed my ticket, but also closed ticked https://github.com/lucide-icons/lucide/issues/560. 

So  is there a chance that icons will be added?
