### ISSUE TITLE
Icon Pix (Brazilian Banks)

### ISSUE THREAD

**Issue by gusperandio** [lucide-icons/lucide#2253] opened 2024-06-24 18:28 UTC
### Icon name

Pix

### Use cases

Currently all banks on brazil use a payment method named PIX, it's a performance to transfer money to person by person or person to company

### Design ideas

![image](https://github.com/lucide-icons/lucide/assets/57372847/7e693f51-f79f-4fd6-a206-f97edd1b441d)

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by karsa-mistmere** [comment] 2024-06-24 18:40
Duplicate of #1899 

The pix logo is protected by copyright, we cannot add this, since we are unable to alter it to fit our guidelines.

https://www.bcb.gov.br/content/estabilidadefinanceira/pix/Regulamento_Pix/I_manual_uso_marca_pix.pdf

**Closed by karsa-mistmere** 2024-06-24 18:40 UTC
Labels: 🙌 icon request
