### ISSUE TITLE
Male and Female Icons

### ISSUE THREAD

**Issue by guysolan** [lucide-icons/lucide#2108] opened 2024-04-27 13:54 UTC
### Icon name

Male, Female

### Use cases

I am working on a medical web app where some features are sex-specific (e.g. Breast and Gynae).

The best way to label such features is with the standard symbols for female ♀ and male ♂.

### Design ideas

Female ♀
Male ♂

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by karsa-mistmere** [comment] 2024-04-27 13:58
Duplicate of #560 and #1581

**Closed by karsa-mistmere** 2024-04-27 13:58 UTC
Labels: 🙌 icon request
