### ISSUE TITLE
Search bar alignment issue on homepage.

### ISSUE THREAD

**Issue by cryptic-pr03** [lucide-icons/lucide#1624] opened 2023-10-21 16:12 UTC
### Browser

- [X] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [ ] Other/not relevant

### Operating system

- [ ] Windows
- [X] Linux
- [ ] macOS
- [ ] Other/not relevant

### Description

The search bar on homepage seems to be misplaced. Aligning it with the icon grid would look better.

### Steps to reproduce

![image](https://github.com/lucide-icons/lucide/assets/92126782/07c11cd3-8f81-4fcf-bdde-5ce16477a858)
The search bar should be shifted to right.

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by ericfennis** [comment] 2023-10-23 08:04
This is by design, but I'm open to discussing this style.
Maybe reduce the length a bit, so it won't look like it is shifted or misaligned?

**Comment by SwastikKasera** [comment] 2023-10-23 08:22
I think, this style might be good, looking for your suggestions @ericfennis 

![Screenshot 2023-10-23 at 13-49-22 Lucide Icons](https://github.com/lucide-icons/lucide/assets/133042995/1379f65f-6ae1-48d1-982f-eef18c5bb5b0)

**Comment by ericfennis** [comment] 2023-12-08 11:38
I close this for now, we leave it as it is for now. See #1627

**Closed by ericfennis** 2023-12-08 11:38 UTC
Labels: 🐛 bug, 👍 good first issue, 🌍 site
