### ISSUE TITLE
Moon Phase Icons

### ISSUE THREAD

**Issue by FleetAdmiralJakob** [lucide-icons/lucide#2218] opened 2024-06-14 07:47 UTC
### Icon name

Moon [Moon Phase] (New, Waxing Crescent, First Quarter, Waxing Gibbous, Full, Waning Gibbous, Third Quarter, Waning Crescent)

### Use cases

To show the moon phase with an icon in my weather app

### Design ideas

![image](https://github.com/lucide-icons/lucide/assets/77451351/5b7389ef-6191-42d6-88e8-2d0fb7f103b4)

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by karsa-mistmere** [comment] 2024-06-14 08:20
Duplicate of #1463

**Closed by karsa-mistmere** 2024-06-14 08:20 UTC
Labels: 🙌 icon request
