### ISSUE TITLE
lucide-react typing for LucideIcon is incorrect

### ISSUE THREAD

**Issue by james-yeoman** [lucide-icons/lucide#1420] opened 2023-07-03 11:41 UTC
`forwardRef` components can't be called, as they're classed as an `ExoticComponent`. `lucide-react` exports the icons using `forwardRef`, but is typed as if it's a regular component. The `LucidIcon` type should be declared as a ForwardRefExoticComponent, in order to correctly reflect the fact that it can't be called.

See [this comment in @types/react index.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/98f892cafa74e0217c7d2b5d87c8cc673365a434/types/react/v17/index.d.ts#L338)

## Prerequisites

* Version: `lucide-react@0.258.0`
* Are you running from source/main: no
* Are you using a released build: yes
* Operating system: Linux
* Bits: 64 bit

## Step to reproduce

 - Create a map of IDs to `LucideIcon` components
   ```tsx
	import type { LucideIcon } from "lucide-react";
	import { Pin, Shield } from "lucide-react";

	type Page = { name: string; url: string; icon: LucideIcon }
	const pages: Page[] = [
		{ name: "Bulletin", url: "/bulletin", icon: Pin},
		{ name: "Account", url: "/account", icon: Shield}
	]
   ```
 - Render the map
   ```tsx
	const NavBar = () => {
		return (
			<div>
				{pages.map(page => (
					<a href={page.url} className="some-navbutton-class">{page.icon({})} {page.name}</a>
				))}
			</div>
		)
	}
   ```
 - Run the app
 - Observe the error in the JS console
 
![image](https://github.com/lucide-icons/lucide/assets/117744792/5d18bca7-ee4b-4c84-963d-112a02ef975f)

### Expected behavior

 - Create a map of IDs to `LucideIcon` components
   ```tsx
	import type { LucideIcon } from "lucide-react";
	import { Pin, Shield } from "lucide-react";

	type Page = { name: string; url: string; icon: LucideIcon }
	const pages: Page[] = [
		{ name: "Bulletin", url: "/bulletin", icon: Pin},
		{ name: "Account", url: "/account", icon: Shield}
	]
   ```
 - Render the map
   ```tsx
	const NavBar = () => {
		return (
			<div>
				{pages.map(page => (
					<a href={page.url} className="some-navbutton-class">{page.icon({})} {page.name}</a>
				))}
			</div>
		)
	}
   ```
 - Observe hover documentation warning that exotic components aren't callable
  
![image](https://github.com/lucide-icons/lucide/assets/117744792/b0950b9c-bae6-486f-bbee-3005f0c575dd)

## Any message or error

 - `Uncaught TypeError: page.icon is not a function`

## Resources

* Links
* Screenshots

Here is what a great bug report would look like:

```
## Prerequisites

Version: Release v3.1.0
Running from: Import using webpack
Operating system: Mac OSX
Bits: 64 bits

## Step to reproduce

 - Import `check` icon
 - Add to a React component/view
 - Run the react app
 - Notice that the `check` isn't rendering correctly which seems a encoding problem
 
### Actual behavior:

 - Import `check` icon
 - Add to a React component/view
 - Run the react app
 - Check is displayed with correct encoding (e.g UTF-8)

## Any message or error

No console output
...

## Resources

No resources
...
```

**Comment by ericfennis** [comment] 2023-07-03 18:38
All icons from `lucide-react` are react components not functions you should call.
You should use JSX instead of calling it as a function, otherwise, unexpected behavior will occur on runtime because React won't see it as a component.

This is how you should render lucide icons in your project:
```tsx
 const NavBar = () => {
    return (
      <div>
          {pages.map(({ url, name, icon: Icon })=> (
              <a href={url} className="some-navbutton-class">
               <Icon />
               {name}
              </a>
          ))}
      </div>
    )
 }
```

There are plenty of articles online explaining in depth why you shouldn't call a React component.
For example https://medium.com/swlh/never-call-a-react-function-component-6815a92b7856

I think the React types are probably designed that way to give this error.

**Comment by james-yeoman** [comment] 2023-07-04 08:51
I know that, but when I've got a map of icons that signify distinct parts of the app, I have to assign the icon to a variable first before I can render it as JSX.

By making `LucideIcon` a `ForwardRefExoticComponent` in the type declarations, it serves as a reminder that "this isn't just a regular component". The types currently indicate that the icons are function components, which is entirely wrong.

What I'm saying is that
```ts
export type LucideIcon = (props: LucideProps) => JSX.Element;
```
should instead be
```ts
export type LucideIcon = ForwardRefExoticComponent<LucideProps>;
```

not only for type correctness, but also because `ExoticComponent` is defined as this
![image](https://github.com/lucide-icons/lucide/assets/117744792/52685cf2-3e1f-46d2-9031-33374be921ed)
which means that there's the warning on hover as well.

**Comment by ericfennis** [comment] 2023-07-07 12:05
Yeah you maybe right, I will try to make a fix for this.

**Closed** 2023-07-13 14:39 UTC
Labels: 🐛 bug
