### ISSUE TITLE
E-Bike

### ISSUE THREAD

**Issue by TheMikeyRoss** [lucide-icons/lucide#1829] opened 2024-01-25 13:44 UTC
### Icon name

Motorbike

### Use cases

For delivery, transportation, delivery apps, shipping

### Design ideas

Something similar to this:
![image](https://github.com/lucide-icons/lucide/assets/97709651/ecc84269-324a-41c5-94b9-345788511a55)

This is my attempt in illustrator but it looks terrible:
![image](https://github.com/lucide-icons/lucide/assets/97709651/3f693e1e-677c-46f1-aa8a-7f27d7dc316a)

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by karsa-mistmere** [comment] 2024-01-25 15:41
I think this is pretty much a duplicate of #915 & #1821

**Closed by karsa-mistmere** 2024-01-25 15:41 UTC
Labels: 🙌 icon request
