### ISSUE TITLE
为什么我没有看到性别的图标 这个很重要

### ISSUE THREAD

**Issue by 2010363329** [lucide-icons/lucide#1757] opened 2023-12-27 06:15 UTC
### Icon name

，

### Use cases

，

### Design ideas

，

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by jguddas** [comment] 2023-12-28 21:42
Duplicate of https://github.com/lucide-icons/lucide/issues/560

**Comment by jguddas** [comment] 2023-12-28 21:42
Duplicate of https://github.com/lucide-icons/lucide/issues/560

**Closed by jguddas** 2023-12-28 21:42 UTC
Labels: 🙌 icon request
