### ISSUE TITLE
Guidelines: Space inside shape.

### ISSUE THREAD

**Issue by jguddas** [lucide-icons/lucide#935] opened 2023-02-03 11:50 UTC
There already is this rule:

> Distinct elements must have 2 pixels of spacing between each other.

But there is no rule for holes inside shapes.

#### Proposal to make the gap 2 px as well

![](https://user-images.githubusercontent.com/25524993/216595354-147f17c5-647c-44aa-b196-89c3696db9b9.png)

**Comment by karsa-mistmere** [comment] 2023-02-03 12:07
These currently do qualify as separate elements and such holes must have a 2px space in preferably all dimensions, but the wording could certainly be improved upon.

**Comment by jguddas** [comment] 2023-02-03 13:15
I like the 2px space in all dimensions guideline, it's not really followed for sharper (<90°) corners tho?

![](https://user-images.githubusercontent.com/25524993/216612065-e4107544-a88c-40e1-8b10-7545387b51a3.png)

**Comment by jguddas** [comment] 2023-02-07 07:22
does this make sens as good vs bad corners?
![image](https://user-images.githubusercontent.com/25524993/217174479-2ca15fde-1a12-444b-a5f6-3e607d62ed50.png)

**Comment by jguddas** [comment] 2023-02-07 09:50
Definitely, legibility over consistency.

What I would love is a script that highlights those errors (maybe even as a GH action).

<img width="100%" src="https://user-images.githubusercontent.com/25524993/217210338-ce29f0c2-93b5-4145-bc47-205a81d3be88.svg"/>

**Comment by karsa-mistmere** [comment] 2023-02-07 10:05
I think this perfectly illustrates why this should be just a suggestion, as in this particular case the suggestions are obviously the bad choice, since human leg, shoulder and arm joints aren't bendy like a rag doll. :)

![image](https://user-images.githubusercontent.com/17746067/217213930-403b1a1d-c99e-4e62-a248-0bebc5749f82.png)

**Comment by jguddas** [comment] 2023-02-11 19:34
I have written a little script that generates a preview and highlights some errors.
- Arc that has a radius of less than 2px is highlighted
- Points that are outside the 2x2/22x22 bounding box are also highlighted to enforce the 1px barrier. 

#### Issues in the accessibility.svg icon for example
- The head is small
- The body is not connected to the wheel
- The wheel could be simplified

<img width="100%" src="https://user-images.githubusercontent.com/25524993/218277360-552e77ea-6f54-4187-8ae6-f829a38dd66a.svg"/>

#### Solution (without changing the head)
<img width="100%" src="https://user-images.githubusercontent.com/25524993/218277194-876ff775-e174-4b59-a76b-ef43901977a1.svg"/>

**Comment by jguddas** [comment] 2023-02-11 19:45
The citrus.svg icon is also a bit problematic.
<img width="100%" src="https://user-images.githubusercontent.com/25524993/218278122-8d4fffaf-33ec-440f-9960-eace9ff5fc8c.svg"/>

**Comment by karsa-mistmere** [comment] 2023-04-27 15:41
Closing this as a duplicate of #650, I've referenced this issue to be considered when the guidelines are eventually rewritten.

**Closed by karsa-mistmere** 2023-04-27 15:41 UTC
Labels: 💡 idea
