### ISSUE TITLE
Vercel/Next.js/React/Node 'too many open files' error

### ISSUE THREAD

**Issue by leeuwd** [lucide-icons/lucide#1446] opened 2023-07-20 13:35 UTC
## Prerequisites

* Version: `lucide-react@0.262.0`, `next@13.4.10`
* Are you running from source/main:  Next.js's Webpack
* Are you using a released build: Yes, https://github.com/lucide-icons/lucide/tree/v0.262.0
* Operating system: Node.js 18.x
* Bits:

## Step to reproduce

Installed using `yarn`, following https://github.com/lucide-icons/lucide/tree/main/packages/lucide-react#lucide-react. 

Error happens when all icons are imported as React Component individually, and also when all icons are imported using Next.js [dynamic import](https://github.com/lucide-icons/lucide/tree/main/packages/lucide-react#lucide-react).

## Any message or error

Error message via Vercel logs:

```
[Error: EMFILE: too many open files, open '/var/task/node_modules/lucide-react/dist/esm/icons/share.mjs'] {
  errno: -24,
  code: 'EMFILE',
  syscall: 'open',
  path: '/var/task/node_modules/lucide-react/dist/esm/icons/share.mjs'
}
[Error: EMFILE: too many open files, open '/var/task/node_modules/lucide-react/dist/esm/icons/share.mjs'] {
  errno: -24,
  code: 'EMFILE',
  syscall: 'open',
  path: '/var/task/node_modules/lucide-react/dist/esm/icons/share.mjs',
  page: '/robots.txt'
}
RequestId: ace94785-66ac-47ca-81d7-ff1ab00793bc Error: Runtime exited without providing a reason
Runtime.ExitError
```

Client side, nothing to go on: 

<img width="347" alt="image" src="https://github.com/lucide-icons/lucide/assets/1755190/20cefd17-d4ba-4bfc-bfd7-c589385a8fad">

## Resources

<img width="625" alt="image" src="https://github.com/lucide-icons/lucide/assets/1755190/8acfbc7a-77f4-4216-8fd5-2967b5226122">

Update; perhaps related?

- https://github.com/vercel/next.js/issues/52646

**Comment by ThimoDEV** [comment] 2023-07-22 12:00
+1

**Comment by leeuwd** [comment] 2023-07-23 08:39
Solved by adding the following to `next.config.js`:

```js
// Modularize Lucide icon imports; otherwise, Vercel
// throws 'too many open files' error (https://github.com/lucide-icons/lucide/issues/1446)
// @see https://nextjs.org/docs/architecture/nextjs-compiler#using-named-imports
modularizeImports: {
  'lucide-react': {
    transform: 'lucide-react/{{member}}',
    skipDefaultConversion: true,
    preventFullImport: true,
  },
},
```

**Comment by Alex-ray** [comment] 2023-07-25 00:23
Tried the `next.config.js` config to no avail.

I'm getting `Module not found: Package path ./UserCircle is not exported from package /apps/web/node_modules/lucide-react (see exports field in /apps/web/node_modules/lucide-react/package.json)` when trying to build.

`"next": "13.4.10"`,  `"lucide-react": "^0.263.0"`

**Comment by leeuwd** [comment] 2023-07-25 07:31
My setup uses the Next.js dynamic import:

```ts
import dynamic from 'next/dynamic'
import { LucideProps } from 'lucide-react'
import dynamicIconImports from 'lucide-react/dynamicIconImports'
import { FunctionComponent } from 'react'

export interface Props extends LucideProps {
  name: keyof typeof dynamicIconImports
}

const SuperIcon: FunctionComponent<Props> = ({ name, ...props }) => {
  const LucideIcon = dynamic(
    dynamicIconImports[name],
    // Loader ensures classname (with Tailwind dimensions) are set and therefore reduce CLS
    { loading: () => <div className={props?.className} aria-hidden={true} /> },
  )

  return <LucideIcon aria-hidden={true} {...props} />
}

export default SuperIcon
```

**Comment by Alex-ray** [comment] 2023-07-25 14:40
Ah that makes sense. @leeuwd a bit tangential but the problem with the dynamic imports is that they flash on load. How are you handling that?

**Comment by smolak** [comment] 2023-07-25 21:19
> Solved by adding the following to `next.config.js`:
> 
> ```js
> // Modularize Lucide icon imports; otherwise, Vercel
> // throws 'too many open files' error (https://github.com/lucide-icons/lucide/issues/1446)
> // @see https://nextjs.org/docs/architecture/nextjs-compiler#using-named-imports
> modularizeImports: {
>   'lucide-react': {
>     transform: 'lucide-react/{{member}}',
>     skipDefaultConversion: true,
>     preventFullImport: true,
>   },
> },
> ```

This is not working, checking locally, and getting:
```
Module not found: Package path ./Check is not exported from package /[path to project]/node_modules/lucide-react (see exports field in /[path to project]/node_modules/lucide-react/package.json)
```

I am on version 0.263.1

**Comment by josephkruse** [comment] 2023-07-25 21:50
I'm also getting the same error as smolak above when I try the modularizeImports fix. Using the latest versions of next and lucide-react:

lucide-react: 0.263.1
next: 13.4.12

It's strange because it was working fine until yesterday.

**Comment by smolak** [comment] 2023-07-26 09:49
> I'm also getting the same error as smolak above when I try the modularizeImports fix. Using the latest versions of next and lucide-react:
> 
> lucide-react: 0.263.1 next: 13.4.12
> 
> It's strange because it was working fine until yesterday.

I checked with the 0.263.0 version, and it did not work. The problem is still there. Unless some older versions did work, but I haven't checked them out.

**Comment by ericfennis** [comment] 2023-07-26 10:49
Related/duplicate issue see #1457.
See my comment in #1457 (possible todo with `.mjs` modules), for the time being try version: 0.261.0

**Comment by cstrnt** [comment] 2023-07-26 10:51
I can confirm that `0.261.0` without `^` etc works fine with Next.js on Vercel

**Comment by smolak** [comment] 2023-07-26 10:54
Hm.... interesting, let me check. I'll get back to you all once tested.

**Comment by smolak** [comment] 2023-07-26 10:57
> I can confirm that `0.261.0` without `^` etc works fine with Next.js on Vercel

What next.config.js confiugration are you using?
This one:
```js
modularizeImports: {
  'lucide-react': {
    transform: 'lucide-react/{{member}}',
    skipDefaultConversion: true,
    preventFullImport: true,
  },
}
```
?

**Comment by smolak** [comment] 2023-07-26 11:28
It works on Vercel, v0.261.0, no configuration added. But, like I mentioned in one comment, that can be just me being below the limit and the problem still being there, as locally I still compile 1000+ more components when the app is run.

**Comment by cstrnt** [comment] 2023-07-26 13:44
> > I can confirm that `0.261.0` without `^` etc works fine with Next.js on Vercel
> 
> What next.config.js confiugration are you using? This one:
> 
> ```js
> modularizeImports: {
>   'lucide-react': {
>     transform: 'lucide-react/{{member}}',
>     skipDefaultConversion: true,
>     preventFullImport: true,
>   },
> }
> ```
> 
> ?
> 
> Asking as this is making the app fail locally:
> 
> ```shell
> Module not found: Can't resolve 'lucide-react/Check'
>   1 | import { Check, ChevronRight, Circle } from "lucide-react";
> ```

There is honestly no way that this option would ever work. The files are in some deeply nested folder which are not specified in the package.json from the lucide-react package

**Comment by Alex-ray** [comment] 2023-07-26 22:03
Confirmed downgrading to `0.261.0` fixed the issues for me as well.

**Comment by smolak** [comment] 2023-07-27 21:08
Good news. NextJS PR just [got merged to canary](https://github.com/vercel/next.js/pull/53051).

**Comment by smolak** [comment] 2023-07-28 21:02
But [there are some problems](https://github.com/vercel/next.js/pull/53051#issuecomment-1656211058) - could you guys cooperate to get this fixed on both sides? :) Would be cool.

**Comment by ericfennis** [comment] 2023-08-04 08:47
Just deployed a nextjs project successfully on Vercel with version `lucide-react@0.263.2-beta.0`. 
@leeuwd Can you check if this version solves your issue?

**Closed** 2023-08-06 13:47 UTC
Labels: 🐛 bug
