### ISSUE TITLE
hangs on vite dev

### ISSUE THREAD

**Issue by xerosanyam** [lucide-icons/lucide#2464] opened 2024-09-15 16:57 UTC
### Package

- [ ] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [ ] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [X] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

0.441.0

### Can you reproduce this in the latest version?

- [X] Yes
- [ ] No

### Browser

- [X] Chrome/Chromium
- [X] Firefox
- [X] Safari
- [X] Edge
- [X] iOS Safari
- [X] Opera
- [ ] Other/not relevant

### Operating system

- [ ] Windows
- [ ] Linux
- [X] macOS
- [ ] ChromeOS
- [ ] iOS
- [ ] Android
- [ ] Other/not relevant

### Description

When I added the package in my sveltekit 2, svelte 5 project, the project stucks at vite dev command.

### Steps to reproduce

1. Create a sveltekit project, choose svelte 5
2. install package
3. npm run dev

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by garraflavatra** [comment] 2024-10-27 15:35
I can confirm this (also Svelte 5, SvelteKit 2).

**Comment by jguddas** [comment] 2024-10-28 07:29
Duplicate of #1944

**Closed by jguddas** 2024-10-28 07:29 UTC
Labels: 🐛 bug
