### ISSUE TITLE
Moto

### ISSUE THREAD

**Issue by aloky** [lucide-icons/lucide#2180] opened 2024-06-04 17:21 UTC
### Icon name

moto

### Use cases

Its a moto icon

### Design ideas

![360_F_134562852_R05hXLbKA2P8lOk53dS0CCNZYFxOZsUq](https://github.com/lucide-icons/lucide/assets/28683905/2f85837d-4660-4235-b9d9-3a22903a8d2c)

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by karsa-mistmere** [comment] 2024-06-04 17:25
Duplicate of #1821 and #915

**Closed by karsa-mistmere** 2024-06-04 17:25 UTC
Labels: 🙌 icon request
