### ISSUE TITLE
Adding classes via `className` in lucide-react removes Lucide classes instead of appending to them

### ISSUE THREAD

**Issue by idahotallpaul** [lucide-icons/lucide#1681] opened 2023-11-16 16:42 UTC
### Package

- [ ] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [X] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

"lucide-react": "^0.292.0",

### Browser

- [ ] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [X] Other/not relevant

### Operating system

- [ ] Windows
- [ ] Linux
- [ ] macOS
- [X] Other/not relevant

## Problem

I wanted to add some conditional formatting to an icon and discovered that when I do, the Lucide classes are removed and I lose the basic Lucide formatting. 

This was unexpected. Styling should be an additive process. Normally, a library supplies the basics, and the user can build on top of that to suit their needs. Requiring the user to re-create the original styling out of the box if they want to extend it is unintuitive. 

## Proposed Solution
Adding classes to an icon should append the user classes after to the library classes, not replace them.

### Current Behavior

Without additional classes:
```jsx
<Star />

// Output:
<svg ... class="lucide lucide-star">...</svg>
```

With additional classes:
```jsx
<Star className={starred ? 'active' : ''} />

// Output:
// starred=false
<svg ... class="">...</svg>

// starred=true
<svg ... class="active">...</svg>
```

### Expected Behavior

Without additional classes:
```jsx
<Star />

// Output:
<svg ... class="lucide lucide-star">...</svg>
```

With additional classes:
```jsx
<Star className={starred ? 'active' : ''} />

// Output:
// starred=false
<svg ... class="lucide lucide-star">...</svg>

// starred=true
<svg ... class="lucide lucide-star active">...</svg>
```

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by karsa-mistmere** [comment] 2023-11-16 16:49
Firstly, to my best knowledge, Lucide does not style any of its icons using CSS or CSS selectors, so I'm not entirely sure what you mean by "the basic Lucide formatting", can you please elaborate on this?

On the other hand, I don't quite know how I feel about this proposal. While at surface level it seems very logical, making CSS classes additive is somewhat problematic because of the following reasons:

1) it would break backwards compatibility - people currently overriding classes would suddenly have extra classes that might have been unwanted the same way you've run into losing some that you didn't want removed
2) opting not to add the default classes to an icon would be impossible (or would require an extra input)

**Comment by idahotallpaul** [comment] 2023-11-16 21:12
Appreciate the quick reply. You're correct that styling is not being applied out of the box. The issue I ran into is that I'm leveraging the `.lucide` class to apply styling to all icons, and when I tried to add a class to an icon for a one-off scenario, it removed that handle. 

In my situation, I'm primarily using the icons in buttons, and my button component has multiple sizes controlled by a `size` property. I'm passing in icons as needed along with any text to display. 

```jsx
<Button size={'sm'|'md'|'lg'}>
  <Star /> Add to Favorites
</Button>
``` 

I want the icons to be consistently sized relative to the font size in my buttons. Since the icon `size` property wants a number, that means on each usage, I'd need to modify both the button size and the icon size. After a while, I realized that even outside of buttons, I was adding the same classes on each usage, which I'd prefer not to do. 

When I started working with the lucide package I saw that each icon rendered with two classes, `lucide lucid-[icon-name]`. The icons offer props so you can style each individual usage of an icon but I didn't see a way to configure usage across the project. Since the classes were present and consistent across the library's markup, I piggybacked on the `.lucide` class to give myself some project wide styling. 

```
.lucide {
    width: 1.25em;
    height: 1.25em;
}
``` 

I'm using tailwind so I added it on the root stylesheet. If I were using sass, I'd probably nest it in the component code. Whether or not Lucide uses them for styling, it's a consistent CSS identifier, so I figured it should be safe to utilize them as needed. And regardless of how I'm adding classes to the icon, the results are the same.

Today I wanted to modify some properties of an icon based on a condition, and when I added a ternary to append a class in the `className`, the icon changed size. The Lucide classes were removed whether the boolean was true or false because the classes the icon renders were overwritten vs appended to.

I can see the concern over backward compatibility, but if people are already adding classes and have styling depending on the `.lucide` class, my guess is they would already have workarounds in place. In my case, I've wrapped the icon in a span tag to apply the styling -- not ideal given that it adds more DOM elements. The other options is to make sure you re-add the lucide classes anytime you add a class of your own, but that's prone to error as well. 

From the standards and expectations standpoint, I think the current behavior is fairly unique. Take a look at most component libraries that ship with their own classes, and chances are they're appending the user's classes at the end of theirs. That's been the case for most I've used, anyway. 

Outside of appending the user classes, another option would be to provide config options for the icons, so users can set the sizing, line thickness, etc. just once for the project. CSS is built in though, and lets the user set those properties and more wherever they want. 

Cheers.

**Comment by ericfennis** [comment] 2023-11-17 13:57
Nice catch @idahotallpaul. I thought we did this already. I checked this throughout all our packages. We do this inconsistently across our packages. Some packages are merging the classes and some are merging them.

Your expected behavior is something that I expect as well. Otherwise applying global styling is not possible anymore.
So I will create a fix for this.

**Comment by idahotallpaul** [comment] 2023-11-17 14:11
Awesome — thanks!

**Closed** 2023-11-24 12:59 UTC
Labels: 🐛 bug
