### ISSUE TITLE
Icons broken in Sketch and Illustrator

### ISSUE THREAD

**Issue by Tinendo** [lucide-icons/lucide#443] opened 2021-11-17 13:36 UTC
The Depiction of the Icons is somehow broken in Adobe Illustrator 2022 (26.0.1) and Sketch (79.1).

It doesn't matter if I download a Package or single SVGs. I also tried to switch from Apple Safari (14.1) to Google Chrome (95.0).

However the Deciption of the downloaded SVGs in Browsers is okay. What am I doing wrong? Or is it a Bug of the SVG-Compression?

**Comment by ericfennis** [comment] 2021-11-17 19:20
@Tinendo Thanks for letting us know. 
How many icons are effected?

**Comment by ericfennis** [comment] 2021-11-17 19:20
I think it it because of the compression/optimizing we doing

**Comment by Tinendo** [comment] 2021-11-17 21:16
@ericfennis I'm sorry! I'm going to attach screenshots tomorrow morning.

**Comment by Tinendo** [comment] 2021-11-18 09:00
@ericfennis Here's an example of the Icon "alarm-check".

<img width="71" alt="alarm-check" src="https://user-images.githubusercontent.com/10920151/142383850-6650dfff-c18e-40a7-9c71-66819701da68.png">

**Comment by SMAH1** [comment] 2021-11-18 10:47
Like this #263
![Untitled](https://user-images.githubusercontent.com/21136680/142401265-a52b0d52-86a0-4d66-a5db-449bc7682b2e.png)

**Comment by ericfennis** [comment] 2021-11-18 13:29
Thanks for posting.
I think the optimize script is a little to aggresive. We need to check all the icons I think

**Comment by hexabinaer** [comment] 2022-01-24 14:14
Hope this helps:

1. Example alarm-check.svg - Illustrator obviously cannot determine the circle's radius
![grafik](https://user-images.githubusercontent.com/1636619/150797871-8d3c15d7-cb5d-48f2-b303-b48229cbba32.png)

2. Affinity Designer can read the icons correctly (in my case, all bookmark-related icons where the bookmark form itself was broken). Converting strokes to forms fixed all similar issues.

**Comment by nkCreation** [comment] 2022-02-09 09:56
I tried to put some spaces between numbers in the SVG code and it works great so I can confirm that the problem come from here.

**Comment by Tinendo** [comment] 2022-02-09 10:09
> I tried to put some spaces between numbers in the SVG code and it works great so I can confirm that the problem come from here.

This is brilliant! Thanks for your effort.

**Comment by ericfennis** [comment] 2022-02-09 19:25
@nkCreation Thanks for the findings!
Definitely somethings went wrong optimizing the icons in #167. But probably won't fix all the issues.
I think we should try revert these changes and check again.

I imported all the icons in illustrator and this was the result.
![WhatsApp Image 2021-12-23 at 13 39 51](https://user-images.githubusercontent.com/11825403/153275105-0c1d2273-81d7-405a-9fb0-4a226f45e4d2.jpeg)

**Closed** 2022-04-06 09:10 UTC
